import type { RoomType } from '@/types';

export const mockRoomTypes: RoomType[] = [
  {
    id: 'RT001',
    code: 'STD',
    name: 'Standard Room',
    description: 'Comfortable room with essential amenities for a pleasant stay.',
    baseRate: 4500,
    maxOccupancy: 2,
    maxAdults: 2,
    maxChildren: 1,
    bedType: 'Queen',
    bedCount: 1,
    size: 28,
    amenities: ['Wi-Fi', 'TV', 'AC', 'Mini Fridge', 'Safe', 'Tea/Coffee Maker'],
    images: ['/images/rooms/standard-1.jpg', '/images/rooms/standard-2.jpg'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'RT002',
    code: 'DLX',
    name: 'Deluxe Room',
    description: 'Spacious room with city view and premium amenities.',
    baseRate: 6500,
    maxOccupancy: 3,
    maxAdults: 2,
    maxChildren: 2,
    bedType: 'King',
    bedCount: 1,
    size: 35,
    amenities: ['Wi-Fi', 'TV', 'AC', 'Mini Bar', 'Safe', 'Tea/Coffee Maker', 'Bathrobe', 'City View'],
    images: ['/images/rooms/deluxe-1.jpg', '/images/rooms/deluxe-2.jpg'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'RT003',
    code: 'PRM',
    name: 'Premier Room',
    description: 'Elegant room with premium furnishings and panoramic views.',
    baseRate: 8500,
    maxOccupancy: 3,
    maxAdults: 2,
    maxChildren: 2,
    bedType: 'King',
    bedCount: 1,
    size: 42,
    amenities: ['Wi-Fi', 'TV', 'AC', 'Mini Bar', 'Safe', 'Tea/Coffee Maker', 'Bathrobe', 'Balcony', 'Panoramic View', 'Espresso Machine'],
    images: ['/images/rooms/premier-1.jpg', '/images/rooms/premier-2.jpg'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'RT004',
    code: 'STE',
    name: 'Executive Suite',
    description: 'Luxurious suite with separate living area and executive amenities.',
    baseRate: 12000,
    maxOccupancy: 4,
    maxAdults: 3,
    maxChildren: 2,
    bedType: 'King',
    bedCount: 1,
    size: 65,
    amenities: ['Wi-Fi', 'Smart TV', 'AC', 'Mini Bar', 'Safe', 'Nespresso Machine', 'Bathrobe', 'Living Area', 'Work Desk', 'Jacuzzi', 'Butler Service'],
    images: ['/images/rooms/suite-1.jpg', '/images/rooms/suite-2.jpg'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'RT005',
    code: 'PRS',
    name: 'Presidential Suite',
    description: 'The pinnacle of luxury with exclusive amenities and personalized service.',
    baseRate: 25000,
    maxOccupancy: 6,
    maxAdults: 4,
    maxChildren: 4,
    bedType: 'King',
    bedCount: 2,
    size: 120,
    amenities: ['Wi-Fi', 'Smart TV', 'AC', 'Full Bar', 'Safe', 'Kitchen', 'Dining Area', 'Private Pool', 'Butler Service', 'Spa Bathroom', 'Private Terrace'],
    images: ['/images/rooms/presidential-1.jpg', '/images/rooms/presidential-2.jpg'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'RT006',
    code: 'FAM',
    name: 'Family Room',
    description: 'Spacious room ideal for families with connecting room option.',
    baseRate: 7500,
    maxOccupancy: 5,
    maxAdults: 2,
    maxChildren: 3,
    bedType: 'Twin',
    bedCount: 2,
    size: 48,
    amenities: ['Wi-Fi', 'TV', 'AC', 'Mini Fridge', 'Safe', 'Tea/Coffee Maker', 'Kids Amenities', 'Connecting Room Available'],
    images: ['/images/rooms/family-1.jpg', '/images/rooms/family-2.jpg'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];
