import type { Tenant, TenantUser, ModuleId } from '@/types';

// ============================================================
// MOCK TENANTS (Hotels)
// ============================================================

export const mockTenants: Tenant[] = [
  {
    id: 'tenant-001',
    name: 'Aurora Grand Hotel',
    slug: 'aurora-grand',
    region: 'India - South',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    planId: 'enterprise',
    status: 'active',
    subscribedAt: '2024-01-15T00:00:00Z',
    enabledModules: ['crs', 'rms', 'ims', 'oms', 'sms', 'bms', 'ams', 'tms', 'as'],
    maxUsers: -1,
    maxRooms: -1,
    contactEmail: 'admin@auroragrand.com',
    contactPhone: '+91-80-4567-8901',
    address: {
      street: '123 MG Road',
      city: 'Bangalore',
      state: 'Karnataka',
      postalCode: '560001',
      country: 'India',
    },
    primaryColor: '#1e88e5',
    userCount: 45,
    roomCount: 220,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-12-01T15:30:00Z',
  },
  {
    id: 'tenant-002',
    name: 'Pacific Breeze Resort',
    slug: 'pacific-breeze',
    region: 'United States - West',
    timezone: 'America/Los_Angeles',
    currency: 'USD',
    planId: 'professional',
    status: 'trial',
    trialEndsAt: '2025-01-15T00:00:00Z',
    enabledModules: ['crs', 'rms', 'bms', 'oms', 'tms', 'ams'],
    maxUsers: 25,
    maxRooms: 150,
    contactEmail: 'manager@pacificbreeze.com',
    contactPhone: '+1-555-234-5678',
    address: {
      street: '456 Ocean Boulevard',
      city: 'Santa Monica',
      state: 'California',
      postalCode: '90401',
      country: 'USA',
    },
    primaryColor: '#13c2c2',
    userCount: 12,
    roomCount: 85,
    createdAt: '2024-11-20T08:00:00Z',
    updatedAt: '2024-12-10T12:00:00Z',
  },
  {
    id: 'tenant-003',
    name: 'Serene Suites',
    slug: 'serene-suites',
    region: 'India - North',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    planId: 'starter',
    status: 'active',
    subscribedAt: '2024-06-01T00:00:00Z',
    enabledModules: ['crs', 'rms'],
    maxUsers: 5,
    maxRooms: 30,
    contactEmail: 'owner@serenesuites.in',
    contactPhone: '+91-11-2345-6789',
    address: {
      street: '78 Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      postalCode: '110001',
      country: 'India',
    },
    primaryColor: '#52c41a',
    userCount: 3,
    roomCount: 24,
    createdAt: '2024-05-28T14:00:00Z',
    updatedAt: '2024-11-15T09:00:00Z',
  },
  {
    id: 'tenant-004',
    name: 'Royal Heritage Palace',
    slug: 'royal-heritage',
    region: 'India - West',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    planId: 'professional',
    status: 'active',
    subscribedAt: '2024-03-01T00:00:00Z',
    enabledModules: ['crs', 'rms', 'bms', 'oms', 'tms', 'ams', 'ims'],
    maxUsers: 25,
    maxRooms: 150,
    contactEmail: 'gm@royalheritage.com',
    contactPhone: '+91-141-456-7890',
    address: {
      street: '1 Palace Road',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302001',
      country: 'India',
    },
    primaryColor: '#2a5298',
    userCount: 18,
    roomCount: 65,
    createdAt: '2024-02-20T11:00:00Z',
    updatedAt: '2024-12-08T16:30:00Z',
  },
  {
    id: 'tenant-005',
    name: 'Marina Bay Suites',
    slug: 'marina-bay',
    region: 'Singapore',
    timezone: 'Asia/Singapore',
    currency: 'SGD',
    planId: 'enterprise',
    status: 'active',
    subscribedAt: '2024-04-15T00:00:00Z',
    enabledModules: ['crs', 'rms', 'ims', 'oms', 'sms', 'bms', 'ams', 'tms', 'as'],
    maxUsers: -1,
    maxRooms: -1,
    contactEmail: 'operations@marinabay.sg',
    contactPhone: '+65-6789-0123',
    address: {
      street: '10 Marina Boulevard',
      city: 'Singapore',
      postalCode: '018983',
      country: 'Singapore',
    },
    primaryColor: '#eb2f96',
    userCount: 62,
    roomCount: 350,
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2024-12-12T10:00:00Z',
  },
  {
    id: 'tenant-006',
    name: 'Budget Stay Inn',
    slug: 'budget-stay',
    region: 'India - South',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    planId: 'starter',
    status: 'suspended',
    subscribedAt: '2024-02-01T00:00:00Z',
    enabledModules: ['crs', 'rms'],
    maxUsers: 5,
    maxRooms: 30,
    contactEmail: 'owner@budgetstay.in',
    contactPhone: '+91-44-2345-6789',
    primaryColor: '#fa8c16',
    userCount: 2,
    roomCount: 18,
    createdAt: '2024-01-28T12:00:00Z',
    updatedAt: '2024-10-01T14:00:00Z',
  },
];

// ============================================================
// MOCK TENANT USERS (Staff within hotels)
// Comprehensive list covering all hotel roles
// ============================================================

export const mockTenantUsers: TenantUser[] = [
  // ============================================================
  // AURORA GRAND HOTEL - Full Enterprise Setup
  // ============================================================
  
  // ADMINISTRATION
  {
    id: 'user-001',
    tenantId: 'tenant-001',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'rajesh.kumar@auroragrand.com',
    phone: '+91-9876543210',
    role: 'hotel_admin',
    department: 'Administration',
    jobTitle: 'General Manager',
    moduleAccess: ['crs', 'rms', 'ims', 'oms', 'sms', 'bms', 'ams', 'tms', 'as'],
    isActive: true,
    lastLoginAt: '2024-12-14T08:30:00Z',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-12-14T08:30:00Z',
  },
  {
    id: 'user-001b',
    tenantId: 'tenant-001',
    firstName: 'Sunita',
    lastName: 'Menon',
    email: 'sunita.menon@auroragrand.com',
    phone: '+91-9876543220',
    role: 'hotel_admin',
    department: 'Administration',
    jobTitle: 'Assistant General Manager',
    moduleAccess: ['crs', 'rms', 'ims', 'oms', 'sms', 'bms', 'ams', 'tms', 'as'],
    isActive: true,
    lastLoginAt: '2024-12-14T07:45:00Z',
    createdBy: 'user-001',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-12-14T07:45:00Z',
  },

  // FRONT OFFICE / RECEPTION
  {
    id: 'user-002',
    tenantId: 'tenant-001',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@auroragrand.com',
    phone: '+91-9876543211',
    role: 'manager',
    department: 'Front Office',
    jobTitle: 'Front Office Manager',
    moduleAccess: ['crs', 'rms', 'bms', 'tms'],
    isActive: true,
    lastLoginAt: '2024-12-14T09:15:00Z',
    createdBy: 'user-001',
    createdAt: '2024-01-20T11:00:00Z',
    updatedAt: '2024-12-14T09:15:00Z',
  },
  {
    id: 'user-003',
    tenantId: 'tenant-001',
    firstName: 'Amit',
    lastName: 'Patel',
    email: 'amit.patel@auroragrand.com',
    phone: '+91-9876543212',
    role: 'supervisor',
    department: 'Front Office',
    jobTitle: 'Front Desk Supervisor',
    moduleAccess: ['crs', 'rms', 'bms'],
    isActive: true,
    lastLoginAt: '2024-12-13T14:00:00Z',
    createdBy: 'user-002',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-12-13T14:00:00Z',
  },
  {
    id: 'user-004',
    tenantId: 'tenant-001',
    firstName: 'Meera',
    lastName: 'Nair',
    email: 'meera.nair@auroragrand.com',
    role: 'staff',
    department: 'Front Office',
    jobTitle: 'Front Desk Agent',
    moduleAccess: ['crs', 'rms'],
    isActive: true,
    createdBy: 'user-002',
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-11-20T11:00:00Z',
  },
  {
    id: 'user-004b',
    tenantId: 'tenant-001',
    firstName: 'Rahul',
    lastName: 'Desai',
    email: 'rahul.desai@auroragrand.com',
    role: 'staff',
    department: 'Front Office',
    jobTitle: 'Night Auditor',
    moduleAccess: ['crs', 'rms', 'bms'],
    isActive: true,
    createdBy: 'user-002',
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-11-25T11:00:00Z',
  },
  {
    id: 'user-004c',
    tenantId: 'tenant-001',
    firstName: 'Neha',
    lastName: 'Kapoor',
    email: 'neha.kapoor@auroragrand.com',
    role: 'staff',
    department: 'Front Office',
    jobTitle: 'Concierge',
    moduleAccess: ['crs', 'tms'],
    isActive: true,
    createdBy: 'user-002',
    createdAt: '2024-05-10T10:00:00Z',
    updatedAt: '2024-12-01T11:00:00Z',
  },

  // HOUSEKEEPING
  {
    id: 'user-007',
    tenantId: 'tenant-001',
    firstName: 'Lakshmi',
    lastName: 'Iyer',
    email: 'lakshmi.iyer@auroragrand.com',
    phone: '+91-9876543217',
    role: 'manager',
    department: 'Housekeeping',
    jobTitle: 'Executive Housekeeper',
    moduleAccess: ['rms', 'ims', 'tms', 'ams'],
    isActive: true,
    lastLoginAt: '2024-12-14T06:00:00Z',
    createdBy: 'user-001',
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2024-12-14T06:00:00Z',
  },
  {
    id: 'user-007b',
    tenantId: 'tenant-001',
    firstName: 'Deepak',
    lastName: 'Verma',
    email: 'deepak.verma@auroragrand.com',
    role: 'supervisor',
    department: 'Housekeeping',
    jobTitle: 'Housekeeping Supervisor',
    moduleAccess: ['rms', 'tms'],
    isActive: true,
    createdBy: 'user-007',
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-10-15T12:00:00Z',
  },
  {
    id: 'user-007c',
    tenantId: 'tenant-001',
    firstName: 'Suman',
    lastName: 'Das',
    email: 'suman.das@auroragrand.com',
    role: 'staff',
    department: 'Housekeeping',
    jobTitle: 'Room Attendant',
    moduleAccess: ['rms', 'tms'],
    isActive: true,
    createdBy: 'user-007',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-11-01T12:00:00Z',
  },

  // FOOD & BEVERAGE
  {
    id: 'user-005',
    tenantId: 'tenant-001',
    firstName: 'Suresh',
    lastName: 'Reddy',
    email: 'suresh.reddy@auroragrand.com',
    phone: '+91-9876543215',
    role: 'manager',
    department: 'Food & Beverage',
    jobTitle: 'F&B Manager',
    moduleAccess: ['oms', 'ims', 'sms', 'bms'],
    isActive: true,
    lastLoginAt: '2024-12-14T07:45:00Z',
    createdBy: 'user-001',
    createdAt: '2024-02-10T08:00:00Z',
    updatedAt: '2024-12-14T07:45:00Z',
  },
  {
    id: 'user-005b',
    tenantId: 'tenant-001',
    firstName: 'Vikrant',
    lastName: 'Saxena',
    email: 'vikrant.saxena@auroragrand.com',
    role: 'supervisor',
    department: 'Food & Beverage',
    jobTitle: 'Restaurant Supervisor',
    moduleAccess: ['oms', 'ims'],
    isActive: true,
    createdBy: 'user-005',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-11-20T12:00:00Z',
  },
  {
    id: 'user-005c',
    tenantId: 'tenant-001',
    firstName: 'Ravi',
    lastName: 'Shankar',
    email: 'ravi.shankar@auroragrand.com',
    role: 'staff',
    department: 'Food & Beverage',
    jobTitle: 'Waiter',
    moduleAccess: ['oms'],
    isActive: true,
    createdBy: 'user-005',
    createdAt: '2024-04-15T10:00:00Z',
    updatedAt: '2024-10-01T12:00:00Z',
  },
  {
    id: 'user-005d',
    tenantId: 'tenant-001',
    firstName: 'Anil',
    lastName: 'Kumar',
    email: 'anil.kumar@auroragrand.com',
    role: 'staff',
    department: 'Food & Beverage',
    jobTitle: 'Room Service',
    moduleAccess: ['oms', 'crs'],
    isActive: true,
    createdBy: 'user-005',
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-11-15T12:00:00Z',
  },

  // FINANCE & ACCOUNTING
  {
    id: 'user-006',
    tenantId: 'tenant-001',
    firstName: 'Kavitha',
    lastName: 'Rao',
    email: 'kavitha.rao@auroragrand.com',
    phone: '+91-9876543216',
    role: 'manager',
    department: 'Finance',
    jobTitle: 'Finance Controller',
    moduleAccess: ['bms', 'as', 'sms'],
    isActive: true,
    lastLoginAt: '2024-12-14T08:00:00Z',
    createdBy: 'user-001',
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2024-12-14T08:00:00Z',
  },
  {
    id: 'user-006b',
    tenantId: 'tenant-001',
    firstName: 'Manoj',
    lastName: 'Gupta',
    email: 'manoj.gupta@auroragrand.com',
    role: 'staff',
    department: 'Finance',
    jobTitle: 'Cashier',
    moduleAccess: ['bms'],
    isActive: true,
    createdBy: 'user-006',
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-11-01T12:00:00Z',
  },

  // MAINTENANCE / ENGINEERING
  {
    id: 'user-008',
    tenantId: 'tenant-001',
    firstName: 'Ramesh',
    lastName: 'Babu',
    email: 'ramesh.babu@auroragrand.com',
    phone: '+91-9876543218',
    role: 'manager',
    department: 'Maintenance',
    jobTitle: 'Chief Engineer',
    moduleAccess: ['rms', 'tms', 'sms', 'ims'],
    isActive: true,
    lastLoginAt: '2024-12-14T06:30:00Z',
    createdBy: 'user-001',
    createdAt: '2024-01-30T10:00:00Z',
    updatedAt: '2024-12-14T06:30:00Z',
  },
  {
    id: 'user-008b',
    tenantId: 'tenant-001',
    firstName: 'Ganesh',
    lastName: 'Pillai',
    email: 'ganesh.pillai@auroragrand.com',
    role: 'staff',
    department: 'Maintenance',
    jobTitle: 'Maintenance Technician',
    moduleAccess: ['rms', 'tms'],
    isActive: true,
    createdBy: 'user-008',
    createdAt: '2024-04-10T10:00:00Z',
    updatedAt: '2024-10-20T12:00:00Z',
  },

  // HR / ADMIN
  {
    id: 'user-009',
    tenantId: 'tenant-001',
    firstName: 'Pooja',
    lastName: 'Hegde',
    email: 'pooja.hegde@auroragrand.com',
    phone: '+91-9876543219',
    role: 'manager',
    department: 'Human Resources',
    jobTitle: 'HR Manager',
    moduleAccess: ['ams', 'tms'],
    isActive: true,
    lastLoginAt: '2024-12-14T09:00:00Z',
    createdBy: 'user-001',
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-12-14T09:00:00Z',
  },

  // ============================================================
  // PACIFIC BREEZE RESORT - Professional Plan
  // ============================================================
  {
    id: 'user-101',
    tenantId: 'tenant-002',
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@pacificbreeze.com',
    phone: '+1-555-234-5679',
    role: 'hotel_admin',
    department: 'Administration',
    jobTitle: 'General Manager',
    moduleAccess: ['crs', 'rms', 'bms', 'oms', 'tms', 'ams'],
    isActive: true,
    lastLoginAt: '2024-12-14T06:30:00Z',
    createdAt: '2024-11-20T08:00:00Z',
    updatedAt: '2024-12-14T06:30:00Z',
  },
  {
    id: 'user-102',
    tenantId: 'tenant-002',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah.williams@pacificbreeze.com',
    role: 'manager',
    department: 'Front Office',
    jobTitle: 'Front Office Manager',
    moduleAccess: ['crs', 'rms', 'bms'],
    isActive: true,
    lastLoginAt: '2024-12-13T18:00:00Z',
    createdBy: 'user-101',
    createdAt: '2024-11-25T10:00:00Z',
    updatedAt: '2024-12-13T18:00:00Z',
  },
  {
    id: 'user-103',
    tenantId: 'tenant-002',
    firstName: 'David',
    lastName: 'Chen',
    email: 'david.chen@pacificbreeze.com',
    role: 'staff',
    department: 'Front Office',
    jobTitle: 'Front Desk Agent',
    moduleAccess: ['crs', 'rms'],
    isActive: true,
    createdBy: 'user-102',
    createdAt: '2024-12-01T09:00:00Z',
    updatedAt: '2024-12-10T14:00:00Z',
  },
  {
    id: 'user-104',
    tenantId: 'tenant-002',
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emily.brown@pacificbreeze.com',
    role: 'supervisor',
    department: 'Housekeeping',
    jobTitle: 'Housekeeping Supervisor',
    moduleAccess: ['rms', 'tms'],
    isActive: true,
    createdBy: 'user-101',
    createdAt: '2024-11-28T10:00:00Z',
    updatedAt: '2024-12-05T14:00:00Z',
  },
  {
    id: 'user-105',
    tenantId: 'tenant-002',
    firstName: 'Carlos',
    lastName: 'Rodriguez',
    email: 'carlos.rodriguez@pacificbreeze.com',
    role: 'manager',
    department: 'Food & Beverage',
    jobTitle: 'F&B Manager',
    moduleAccess: ['oms', 'bms'],
    isActive: true,
    createdBy: 'user-101',
    createdAt: '2024-11-30T10:00:00Z',
    updatedAt: '2024-12-08T14:00:00Z',
  },

  // ============================================================
  // SERENE SUITES - Starter Plan (Small guesthouse)
  // ============================================================
  {
    id: 'user-201',
    tenantId: 'tenant-003',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram.singh@serenesuites.in',
    phone: '+91-11-9876543210',
    role: 'hotel_admin',
    department: 'Administration',
    jobTitle: 'Owner / Manager',
    moduleAccess: ['crs', 'rms'],
    isActive: true,
    lastLoginAt: '2024-12-14T09:00:00Z',
    createdAt: '2024-05-28T14:00:00Z',
    updatedAt: '2024-12-14T09:00:00Z',
  },
  {
    id: 'user-202',
    tenantId: 'tenant-003',
    firstName: 'Anita',
    lastName: 'Gupta',
    email: 'anita.gupta@serenesuites.in',
    role: 'staff',
    department: 'Front Office',
    jobTitle: 'Receptionist',
    moduleAccess: ['crs', 'rms'],
    isActive: true,
    createdBy: 'user-201',
    createdAt: '2024-06-10T10:00:00Z',
    updatedAt: '2024-11-01T11:00:00Z',
  },
  {
    id: 'user-203',
    tenantId: 'tenant-003',
    firstName: 'Raju',
    lastName: 'Prasad',
    email: 'raju.prasad@serenesuites.in',
    role: 'staff',
    department: 'Housekeeping',
    jobTitle: 'Caretaker',
    moduleAccess: ['rms'],
    isActive: true,
    createdBy: 'user-201',
    createdAt: '2024-07-01T10:00:00Z',
    updatedAt: '2024-10-15T11:00:00Z',
  },

  // ============================================================
  // ROYAL HERITAGE PALACE - Professional Plan
  // ============================================================
  {
    id: 'user-301',
    tenantId: 'tenant-004',
    firstName: 'Arjun',
    lastName: 'Rathore',
    email: 'arjun.rathore@royalheritage.com',
    phone: '+91-141-9876543210',
    role: 'hotel_admin',
    department: 'Administration',
    jobTitle: 'General Manager',
    moduleAccess: ['crs', 'rms', 'bms', 'oms', 'tms', 'ams', 'ims'],
    isActive: true,
    lastLoginAt: '2024-12-14T08:45:00Z',
    createdAt: '2024-02-20T11:00:00Z',
    updatedAt: '2024-12-14T08:45:00Z',
  },
  {
    id: 'user-302',
    tenantId: 'tenant-004',
    firstName: 'Padmini',
    lastName: 'Devi',
    email: 'padmini.devi@royalheritage.com',
    role: 'manager',
    department: 'Front Office',
    jobTitle: 'Front Office Manager',
    moduleAccess: ['crs', 'rms', 'bms', 'tms'],
    isActive: true,
    createdBy: 'user-301',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-12-01T11:00:00Z',
  },
  {
    id: 'user-303',
    tenantId: 'tenant-004',
    firstName: 'Bharat',
    lastName: 'Sharma',
    email: 'bharat.sharma@royalheritage.com',
    role: 'supervisor',
    department: 'Front Office',
    jobTitle: 'Duty Manager',
    moduleAccess: ['crs', 'rms', 'bms'],
    isActive: true,
    createdBy: 'user-302',
    createdAt: '2024-04-15T10:00:00Z',
    updatedAt: '2024-11-20T11:00:00Z',
  },
  {
    id: 'user-304',
    tenantId: 'tenant-004',
    firstName: 'Geeta',
    lastName: 'Meena',
    email: 'geeta.meena@royalheritage.com',
    role: 'staff',
    department: 'Front Office',
    jobTitle: 'Receptionist',
    moduleAccess: ['crs', 'rms'],
    isActive: true,
    createdBy: 'user-302',
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-10-15T11:00:00Z',
  },
  {
    id: 'user-305',
    tenantId: 'tenant-004',
    firstName: 'Mohan',
    lastName: 'Lal',
    email: 'mohan.lal@royalheritage.com',
    role: 'manager',
    department: 'Food & Beverage',
    jobTitle: 'F&B Manager',
    moduleAccess: ['oms', 'ims', 'bms'],
    isActive: true,
    createdBy: 'user-301',
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-11-01T11:00:00Z',
  },

  // ============================================================
  // MARINA BAY SUITES - Enterprise Plan
  // ============================================================
  {
    id: 'user-401',
    tenantId: 'tenant-005',
    firstName: 'Wei Lin',
    lastName: 'Tan',
    email: 'weilin.tan@marinabay.sg',
    phone: '+65-9123-4567',
    role: 'hotel_admin',
    department: 'Administration',
    jobTitle: 'General Manager',
    moduleAccess: ['crs', 'rms', 'ims', 'oms', 'sms', 'bms', 'ams', 'tms', 'as'],
    isActive: true,
    lastLoginAt: '2024-12-14T09:30:00Z',
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2024-12-14T09:30:00Z',
  },
  {
    id: 'user-402',
    tenantId: 'tenant-005',
    firstName: 'Jessica',
    lastName: 'Lee',
    email: 'jessica.lee@marinabay.sg',
    role: 'manager',
    department: 'Front Office',
    jobTitle: 'Director of Rooms',
    moduleAccess: ['crs', 'rms', 'bms', 'tms'],
    isActive: true,
    lastLoginAt: '2024-12-14T08:15:00Z',
    createdBy: 'user-401',
    createdAt: '2024-04-20T10:00:00Z',
    updatedAt: '2024-12-14T08:15:00Z',
  },
  {
    id: 'user-403',
    tenantId: 'tenant-005',
    firstName: 'Kevin',
    lastName: 'Ng',
    email: 'kevin.ng@marinabay.sg',
    role: 'supervisor',
    department: 'Front Office',
    jobTitle: 'Guest Relations Manager',
    moduleAccess: ['crs', 'rms', 'bms'],
    isActive: true,
    createdBy: 'user-402',
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-11-15T11:00:00Z',
  },
  {
    id: 'user-404',
    tenantId: 'tenant-005',
    firstName: 'Priscilla',
    lastName: 'Wong',
    email: 'priscilla.wong@marinabay.sg',
    role: 'staff',
    department: 'Front Office',
    jobTitle: 'Front Desk Agent',
    moduleAccess: ['crs', 'rms'],
    isActive: true,
    createdBy: 'user-402',
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-10-20T11:00:00Z',
  },
  {
    id: 'user-405',
    tenantId: 'tenant-005',
    firstName: 'Marcus',
    lastName: 'Lim',
    email: 'marcus.lim@marinabay.sg',
    role: 'manager',
    department: 'Finance',
    jobTitle: 'Finance Director',
    moduleAccess: ['bms', 'as', 'sms'],
    isActive: true,
    createdBy: 'user-401',
    createdAt: '2024-04-25T10:00:00Z',
    updatedAt: '2024-12-01T11:00:00Z',
  },
  {
    id: 'user-406',
    tenantId: 'tenant-005',
    firstName: 'Sharon',
    lastName: 'Koh',
    email: 'sharon.koh@marinabay.sg',
    role: 'manager',
    department: 'Housekeeping',
    jobTitle: 'Executive Housekeeper',
    moduleAccess: ['rms', 'ims', 'tms', 'ams'],
    isActive: true,
    createdBy: 'user-401',
    createdAt: '2024-05-10T10:00:00Z',
    updatedAt: '2024-11-25T11:00:00Z',
  },
  {
    id: 'user-407',
    tenantId: 'tenant-005',
    firstName: 'Daniel',
    lastName: 'Chia',
    email: 'daniel.chia@marinabay.sg',
    role: 'manager',
    department: 'Food & Beverage',
    jobTitle: 'F&B Director',
    moduleAccess: ['oms', 'ims', 'sms', 'bms'],
    isActive: true,
    createdBy: 'user-401',
    createdAt: '2024-04-30T10:00:00Z',
    updatedAt: '2024-12-05T11:00:00Z',
  },
];

// Helper functions
export const getTenantById = (id: string): Tenant | undefined => {
  return mockTenants.find(t => t.id === id);
};

export const getTenantBySlug = (slug: string): Tenant | undefined => {
  return mockTenants.find(t => t.slug === slug);
};

export const getUsersByTenantId = (tenantId: string): TenantUser[] => {
  return mockTenantUsers.filter(u => u.tenantId === tenantId);
};

export const getTenantStats = () => {
  const total = mockTenants.length;
  const active = mockTenants.filter(t => t.status === 'active').length;
  const trial = mockTenants.filter(t => t.status === 'trial').length;
  const suspended = mockTenants.filter(t => t.status === 'suspended').length;
  
  const byPlan = {
    starter: mockTenants.filter(t => t.planId === 'starter').length,
    professional: mockTenants.filter(t => t.planId === 'professional').length,
    enterprise: mockTenants.filter(t => t.planId === 'enterprise').length,
  };
  
  const totalUsers = mockTenantUsers.length;
  const totalRooms = mockTenants.reduce((sum, t) => sum + (t.roomCount || 0), 0);
  
  return {
    total,
    active,
    trial,
    suspended,
    byPlan,
    totalUsers,
    totalRooms,
  };
};
