import type { Guest, GuestVipStatus } from '@/types';

export const mockGuests: Guest[] = [
  {
    id: 'G001',
    tenantId: 'tenant-001', // CRITICAL: Tenant isolation
    firstName: 'Rajesh',
    lastName: 'Sharma',
    email: 'rajesh.sharma@email.com',
    phone: '+91-9876543210',
    nationality: 'India',
    address: {
      street: '123 MG Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400001',
      country: 'India',
    },
    idType: 'passport',
    idNumber: 'P1234567',
    vipStatus: 'gold',
    preferences: {
      roomType: 'Deluxe',
      floorPreference: 'high',
      bedType: 'king',
      smokingRoom: false,
      dietaryRestrictions: ['Vegetarian'],
    },
    totalStays: 12,
    totalSpend: 145000,
    lastStayDate: '2024-11-15',
    tags: ['Frequent', 'Business'],
    createdAt: '2023-01-15T10:30:00Z',
    updatedAt: '2024-11-15T14:00:00Z',
  },
  {
    id: 'G002',
    tenantId: 'tenant-001', // CRITICAL: Tenant isolation
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya.patel@company.com',
    phone: '+91-9887766554',
    nationality: 'India',
    address: {
      street: '456 Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500033',
      country: 'India',
    },
    idType: 'national_id',
    idNumber: 'AAAPZ1234C',
    vipStatus: 'platinum',
    preferences: {
      roomType: 'Suite',
      floorPreference: 'high',
      bedType: 'king',
      smokingRoom: false,
    },
    totalStays: 28,
    totalSpend: 520000,
    lastStayDate: '2024-12-01',
    tags: ['VIP', 'Corporate', 'Long Stay'],
    createdAt: '2022-06-10T09:00:00Z',
    updatedAt: '2024-12-01T11:00:00Z',
  },
  {
    id: 'G003',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@gmail.com',
    phone: '+1-555-0123',
    nationality: 'United States',
    address: {
      street: '789 5th Avenue',
      city: 'New York',
      state: 'NY',
      postalCode: '10022',
      country: 'USA',
    },
    idType: 'passport',
    idNumber: 'US12345678',
    vipStatus: 'silver',
    preferences: {
      roomType: 'Premier',
      floorPreference: 'any',
      bedType: 'king',
      smokingRoom: false,
      dietaryRestrictions: ['Gluten-Free'],
    },
    totalStays: 5,
    totalSpend: 78000,
    lastStayDate: '2024-10-20',
    tags: ['International'],
    createdAt: '2024-03-01T15:00:00Z',
    updatedAt: '2024-10-20T16:00:00Z',
  },
  {
    id: 'G004',
    firstName: 'Anika',
    lastName: 'Mehta',
    email: 'anika.mehta@techcorp.in',
    phone: '+91-9123456789',
    nationality: 'India',
    address: {
      street: '321 Koramangala',
      city: 'Bangalore',
      state: 'Karnataka',
      postalCode: '560034',
      country: 'India',
    },
    idType: 'driving_license',
    idNumber: 'KA09-20190012345',
    vipStatus: 'none',
    preferences: {
      roomType: 'Standard',
      bedType: 'queen',
      smokingRoom: false,
    },
    totalStays: 2,
    totalSpend: 12000,
    lastStayDate: '2024-09-10',
    tags: ['Business'],
    createdAt: '2024-07-01T12:00:00Z',
    updatedAt: '2024-09-10T10:00:00Z',
  },
  {
    id: 'G005',
    firstName: 'Mohammed',
    lastName: 'Al Rashid',
    email: 'm.alrashid@emirates.ae',
    phone: '+971-50-1234567',
    nationality: 'United Arab Emirates',
    address: {
      street: 'Downtown Dubai',
      city: 'Dubai',
      postalCode: '00000',
      country: 'UAE',
    },
    idType: 'passport',
    idNumber: 'AE98765432',
    vipStatus: 'platinum',
    preferences: {
      roomType: 'Presidential Suite',
      floorPreference: 'high',
      bedType: 'king',
      smokingRoom: false,
      specialRequests: 'Halal food only, Arabic newspapers',
    },
    totalStays: 8,
    totalSpend: 890000,
    lastStayDate: '2024-11-28',
    tags: ['VIP', 'International', 'Suite Guest'],
    createdAt: '2023-05-15T08:00:00Z',
    updatedAt: '2024-11-28T20:00:00Z',
  },
  {
    id: 'G006',
    firstName: 'Sakura',
    lastName: 'Tanaka',
    email: 'sakura.tanaka@mail.jp',
    phone: '+81-90-1234-5678',
    nationality: 'Japan',
    address: {
      street: '1-2-3 Shibuya',
      city: 'Tokyo',
      postalCode: '150-0002',
      country: 'Japan',
    },
    idType: 'passport',
    idNumber: 'JP45678901',
    vipStatus: 'gold',
    preferences: {
      roomType: 'Deluxe',
      floorPreference: 'low',
      bedType: 'twin',
      smokingRoom: false,
    },
    totalStays: 6,
    totalSpend: 95000,
    lastStayDate: '2024-11-01',
    tags: ['International', 'Leisure'],
    createdAt: '2023-09-20T11:00:00Z',
    updatedAt: '2024-11-01T09:00:00Z',
  },
  {
    id: 'G007',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram.singh@corporate.com',
    phone: '+91-9988776655',
    nationality: 'India',
    address: {
      street: '55 Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      postalCode: '110001',
      country: 'India',
    },
    idType: 'national_id',
    idNumber: 'DELPV1234K',
    vipStatus: 'silver',
    preferences: {
      roomType: 'Premier',
      floorPreference: 'high',
      bedType: 'king',
      smokingRoom: false,
    },
    totalStays: 9,
    totalSpend: 125000,
    lastStayDate: '2024-12-05',
    tags: ['Corporate', 'Frequent'],
    createdAt: '2023-04-10T14:00:00Z',
    updatedAt: '2024-12-05T12:00:00Z',
  },
  {
    id: 'G008',
    firstName: 'Lisa',
    lastName: 'Mueller',
    email: 'lisa.mueller@gmail.de',
    phone: '+49-176-12345678',
    nationality: 'Germany',
    address: {
      street: 'Friedrichstrasse 100',
      city: 'Berlin',
      postalCode: '10117',
      country: 'Germany',
    },
    idType: 'passport',
    idNumber: 'DE12345678',
    vipStatus: 'none',
    preferences: {
      roomType: 'Deluxe',
      bedType: 'queen',
      smokingRoom: false,
      dietaryRestrictions: ['Vegan'],
    },
    totalStays: 1,
    totalSpend: 18500,
    lastStayDate: '2024-12-10',
    tags: ['New', 'International', 'Leisure'],
    createdAt: '2024-12-08T16:00:00Z',
    updatedAt: '2024-12-10T08:00:00Z',
  },
  {
    id: 'G009',
    firstName: 'Amit',
    lastName: 'Kapoor',
    email: 'amit.kapoor@email.com',
    phone: '+91-9876512340',
    nationality: 'India',
    address: {
      street: '78 Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      postalCode: '700016',
      country: 'India',
    },
    idType: 'passport',
    idNumber: 'P9876543',
    vipStatus: 'gold',
    preferences: {
      roomType: 'Executive Suite',
      floorPreference: 'high',
      bedType: 'king',
      smokingRoom: false,
    },
    totalStays: 15,
    totalSpend: 285000,
    lastStayDate: '2024-12-08',
    tags: ['VIP', 'Business', 'Frequent'],
    createdAt: '2022-11-01T10:00:00Z',
    updatedAt: '2024-12-08T14:00:00Z',
  },
  {
    id: 'G010',
    firstName: 'Chen',
    lastName: 'Wei',
    email: 'chen.wei@mail.cn',
    phone: '+86-138-1234-5678',
    nationality: 'China',
    address: {
      street: '888 Nanjing Road',
      city: 'Shanghai',
      postalCode: '200000',
      country: 'China',
    },
    idType: 'passport',
    idNumber: 'CN88776655',
    vipStatus: 'platinum',
    preferences: {
      roomType: 'Presidential Suite',
      floorPreference: 'high',
      bedType: 'king',
      smokingRoom: false,
      specialRequests: 'Chinese tea service, Mandarin speaking staff',
    },
    totalStays: 4,
    totalSpend: 450000,
    lastStayDate: '2024-11-20',
    tags: ['VIP', 'International', 'Suite Guest'],
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2024-11-20T18:00:00Z',
  },
];

// Generate more guests programmatically
const firstNames = ['Ravi', 'Sita', 'Arjun', 'Kavita', 'Suresh', 'Meena', 'Deepak', 'Anjali', 'Rahul', 'Pooja'];
const lastNames = ['Kumar', 'Verma', 'Gupta', 'Reddy', 'Nair', 'Iyer', 'Joshi', 'Rao', 'Mishra', 'Das'];
const vipStatuses: GuestVipStatus[] = ['none', 'none', 'none', 'silver', 'silver', 'gold'];

for (let i = 11; i <= 50; i++) {
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
  const vipStatus = vipStatuses[Math.floor(Math.random() * vipStatuses.length)];
  const totalStays = Math.floor(Math.random() * 10);
  
  mockGuests.push({
    id: `G${String(i).padStart(3, '0')}`,
    tenantId: 'tenant-001', // CRITICAL: Tenant isolation
    firstName,
    lastName,
    email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}${i}@email.com`,
    phone: `+91-${9000000000 + Math.floor(Math.random() * 999999999)}`,
    nationality: 'India',
    vipStatus,
    totalStays,
    totalSpend: totalStays * (5000 + Math.floor(Math.random() * 10000)),
    tags: totalStays > 5 ? ['Frequent'] : [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
  });
}
