import type { PurchaseOrder, PurchaseOrderItem } from '@/types';
import dayjs from 'dayjs';

const mockPOItems: PurchaseOrderItem[] = [
  {
    id: 'poi-001',
    itemId: 'inv-001',
    description: 'Premium Coffee Beans - Arabica',
    quantity: 50,
    receivedQuantity: 0,
    unitPrice: 900,
    totalPrice: 45000,
  },
  {
    id: 'poi-002',
    itemId: 'inv-002',
    description: 'Fresh Milk - Full Cream',
    quantity: 200,
    receivedQuantity: 0,
    unitPrice: 60,
    totalPrice: 12000,
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-001',
    tenantId: 'tenant-001',
    poNumber: 'PO-2024-001',
    vendorId: 'v1',
    status: 'sent',
    items: mockPOItems,
    subtotal: 57000,
    taxAmount: 10260,
    shippingCost: 500,
    totalAmount: 67760,
    currency: 'INR',
    expectedDeliveryDate: dayjs().add(3, 'day').format('YYYY-MM-DD'),
    deliveryAddress: 'Hotel Main Entrance, Dock A',
    notes: 'Please deliver during morning hours (8 AM - 12 PM)',
    createdBy: 'user1',
    sentAt: dayjs().subtract(1, 'day').toISOString(),
    createdAt: dayjs().subtract(2, 'day').toISOString(),
    updatedAt: dayjs().subtract(1, 'day').toISOString(),
  },
  {
    id: 'po-002',
    tenantId: 'tenant-001',
    poNumber: 'PO-2024-002',
    vendorId: 'v2',
    status: 'approved',
    items: [
      {
        id: 'poi-003',
        itemId: 'inv-003',
        description: 'Luxury Bed Linens - King Size',
        quantity: 100,
        receivedQuantity: 0,
        unitPrice: 280,
        totalPrice: 28000,
      },
    ],
    subtotal: 28000,
    taxAmount: 5040,
    shippingCost: 0,
    totalAmount: 33040,
    currency: 'INR',
    expectedDeliveryDate: dayjs().add(5, 'day').format('YYYY-MM-DD'),
    createdBy: 'user1',
    approvedBy: 'user1',
    approvedAt: dayjs().subtract(1, 'hour').toISOString(),
    createdAt: dayjs().subtract(1, 'day').toISOString(),
    updatedAt: dayjs().subtract(1, 'hour').toISOString(),
  },
  {
    id: 'po-003',
    tenantId: 'tenant-001',
    poNumber: 'PO-2024-003',
    vendorId: 'v3',
    status: 'received',
    items: [
      {
        id: 'poi-004',
        itemId: 'inv-004',
        description: 'Cleaning Chemicals - Multi-purpose',
        quantity: 50,
        receivedQuantity: 50,
        unitPrice: 370,
        totalPrice: 18500,
      },
    ],
    subtotal: 18500,
    taxAmount: 3330,
    shippingCost: 200,
    totalAmount: 22030,
    currency: 'INR',
    createdBy: 'user1',
    createdAt: dayjs().subtract(10, 'day').toISOString(),
    updatedAt: dayjs().subtract(5, 'day').toISOString(),
  },
  {
    id: 'po-004',
    tenantId: 'tenant-001',
    poNumber: 'PO-2024-004',
    vendorId: 'v1',
    status: 'pending_approval',
    items: [
      {
        id: 'poi-005',
        itemId: 'inv-005',
        description: 'Fresh Vegetables - Mixed',
        quantity: 150,
        receivedQuantity: 0,
        unitPrice: 80,
        totalPrice: 12000,
      },
    ],
    subtotal: 12000,
    taxAmount: 2160,
    shippingCost: 300,
    totalAmount: 14460,
    currency: 'INR',
    expectedDeliveryDate: dayjs().add(2, 'day').format('YYYY-MM-DD'),
    createdBy: 'user1',
    createdAt: dayjs().subtract(2, 'hour').toISOString(),
    updatedAt: dayjs().subtract(2, 'hour').toISOString(),
  },
  {
    id: 'po-005',
    tenantId: 'tenant-001',
    poNumber: 'PO-2024-005',
    vendorId: 'v2',
    status: 'draft',
    items: [
      {
        id: 'poi-006',
        itemId: 'inv-006',
        description: 'Bath Towels - Premium',
        quantity: 200,
        receivedQuantity: 0,
        unitPrice: 450,
        totalPrice: 90000,
      },
    ],
    subtotal: 90000,
    taxAmount: 16200,
    shippingCost: 0,
    totalAmount: 106200,
    currency: 'INR',
    createdBy: 'user1',
    createdAt: dayjs().subtract(30, 'minute').toISOString(),
    updatedAt: dayjs().subtract(30, 'minute').toISOString(),
  },
];

